/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views.Management;

import Core.Globals;
import Model.Article.Shop;
import Model.Article.Tables.ShopTableModel;
import Model.Views.BaseView;
import java.util.ArrayList;
import java.util.List;
import javax.swing.border.TitledBorder;

/**
 *
 * @author noldi
 */
public class ManageShopsDialog extends javax.swing.JDialog implements BaseView
{    
    private List<Shop> Shops = new ArrayList<>();
    /**
     * Creates new form AddArticleDialog
     */
    public ManageShopsDialog(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(parent);
        
        this.LoadLocalization();     
        
        this.FillValues();
    }
   
    @Override
    public  void LoadSettings()
    {
    
    }
    
    @Override
    public  void LoadLocalization()
    {
        // Dialog Title
        this.setTitle(Globals.LanguageEngine.Translate(Globals.LanguageEngine.Translate("DIALOG_ADD_TITLE")));
        
        /****** ArticleBox ******/
        // Title
        ((TitledBorder)this.ArticlePanel.getBorder()).setTitle(Globals.LanguageEngine.Translate("GENERAL_CATEGORY_INFORMATION"));
        
        // Controls
        this.CategoryIDLabel.setText(Globals.LanguageEngine.Translate("SYSTEM_CONTROLS_ARTICLE_ID"));
        this.CategoryNameLabel.setText(Globals.LanguageEngine.Translate("SYSTEM_CONTROLS_ARTICLE_NAME"));
        this.CategoryDescriptionLabel.setText(Globals.LanguageEngine.Translate("SYSTEM_CONTROLS_ARTICLE_DESCRIPTION"));        
    }
    
    private void FillValues()
    {
        for (Shop shop : Globals.Database.LoadAll(Shop.class))
        {
            this.Shops.add(shop);            
        }
        
        this.CategoryTable.setModel(new ShopTableModel(this.Shops));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanel = new javax.swing.JScrollPane();
        ContentPanel = new javax.swing.JPanel();
        ArticlePanel = new javax.swing.JPanel();
        CategoryIDLabel = new javax.swing.JLabel();
        CategoryIDTextField = new javax.swing.JTextField();
        CategoryNameLabel = new javax.swing.JLabel();
        CategoryNameTextField = new javax.swing.JTextField();
        CategoryDescriptionLabel = new javax.swing.JLabel();
        CategoryDescriptionTextField = new javax.swing.JTextField();
        OkButton = new javax.swing.JButton();
        DeleteSelectedCategoryButton = new javax.swing.JButton();
        SaveSelectedCategoryButton = new javax.swing.JButton();
        CategoryTableScrollPane = new javax.swing.JScrollPane();
        CategoryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        ArticlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Shop"));

        CategoryIDLabel.setLabelFor(CategoryIDTextField);
        CategoryIDLabel.setText("ID");

        CategoryIDTextField.setEditable(false);

        CategoryNameLabel.setLabelFor(CategoryNameTextField);
        CategoryNameLabel.setText("Name");

        CategoryDescriptionLabel.setLabelFor(CategoryDescriptionTextField);
        CategoryDescriptionLabel.setText("Description");
        CategoryDescriptionLabel.setToolTipText("");

        javax.swing.GroupLayout ArticlePanelLayout = new javax.swing.GroupLayout(ArticlePanel);
        ArticlePanel.setLayout(ArticlePanelLayout);
        ArticlePanelLayout.setHorizontalGroup(
            ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArticlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CategoryIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CategoryNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryDescriptionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CategoryNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CategoryIDTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ArticlePanelLayout.setVerticalGroup(
            ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArticlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryIDLabel)
                    .addComponent(CategoryIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryNameLabel)
                    .addComponent(CategoryNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ArticlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryDescriptionLabel)
                    .addComponent(CategoryDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OkButton.setText("Ok");

        DeleteSelectedCategoryButton.setText("Delete");
        DeleteSelectedCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSelectedCategoryButtonActionPerformed(evt);
            }
        });

        SaveSelectedCategoryButton.setText("Save");

        CategoryTable.setAutoCreateRowSorter(true);
        CategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CategoryTableScrollPane.setViewportView(CategoryTable);

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addComponent(DeleteSelectedCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(440, 440, 440)
                        .addComponent(SaveSelectedCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CategoryTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArticlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addComponent(ArticlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveSelectedCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSelectedCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CategoryTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ScrollPanel.setViewportView(ContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteSelectedCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSelectedCategoryButtonActionPerformed

    }//GEN-LAST:event_DeleteSelectedCategoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageShopsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageShopsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageShopsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageShopsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageShopsDialog dialog = new ManageShopsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ArticlePanel;
    private javax.swing.JLabel CategoryDescriptionLabel;
    private javax.swing.JTextField CategoryDescriptionTextField;
    private javax.swing.JLabel CategoryIDLabel;
    private javax.swing.JTextField CategoryIDTextField;
    private javax.swing.JLabel CategoryNameLabel;
    private javax.swing.JTextField CategoryNameTextField;
    private javax.swing.JTable CategoryTable;
    private javax.swing.JScrollPane CategoryTableScrollPane;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JButton DeleteSelectedCategoryButton;
    private javax.swing.JButton OkButton;
    private javax.swing.JButton SaveSelectedCategoryButton;
    private javax.swing.JScrollPane ScrollPanel;
    // End of variables declaration//GEN-END:variables
}
